### ISSUE TITLE
[node edit] WeakReference serialized as array instead of scalar

### ISSUE THREAD

**Issue by dantleech** [phpcr/phpcr-shell#146]
In the following example shows the representation of `nsys:redirect-target` in the `node:edit` output. The value is infact a scalar value.

````
'nsys:redirect-target':
    type: WeakReference
    value: [8ade6951-860d-40cc-864f-ce6946957845]
````

**Comment by dbu** [comment]
and nsys:redirect-target is not a multivalue field?

**Comment by dantleech** [comment]
Nope. Think its some problem with the serializer, wouldn't be the first..
