### ISSUE TITLE
Show property only shows single line (and it trucates that line)

### ISSUE THREAD

**Issue by dantleech** [phpcr/phpcr-shell#152]

**Comment by alexander-schranz** [comment]
:+1: for none truncated output

**Comment by dantleech** [comment]
This was actually fixed in e80427632e19ba0b9c7018c209e28e267217dc85

**Comment by dantleech** [comment]
. but for some reason was not part of the beta3 tag which was tagged after that commit :( trying to do a new release.

**Comment by dantleech** [comment]
Released https://github.com/phpcr/phpcr-shell/releases/tag/beta4
