### ISSUE TITLE
copy-pasting multiline queries

### ISSUE THREAD

**Issue by dbu** [phpcr/phpcr-shell#161]
when copy-pasting, only the first line of the query gets pasted, so i have to paste line by line

**Comment by dantleech** [comment]
You mean concatenate the lines manually?

How could we avoid that?

**Comment by dbu** [comment]
actually i was tricked by #162 into thinking the paste had not kept the lines... they only appear after the previous line was executed

**Comment by dantleech** [comment]
But this is still an issue I think .. we need to not execute commands on a line break when the "command" is a query.

**Comment by dbu** [comment]
yep, that is #162
