### ISSUE TITLE
auto-executing queries is dangerous

### ISSUE THREAD

**Issue by dbu** [phpcr/phpcr-shell#162]
when copy-pasting a query like this:

```
UPDATE [nt:unstructured] AS a INNER JOIN [nt:unstructured] AS t ON ISCHILDNODE(t, a) 
SET expr('row.getNode("t").setProperty("originalLinkCaption", row.getNode("a").getPropertyValue("originalLinkCaption"))') 
WHERE a.[phpcr:class] = 'Liipch\MagazineBundle\Document\Article' ;
```

it gets already executed after the first row. if i had UPDATE and SET on the same line (and working) but not the WHERE, this could lead to data destruction.

i propose that as with mysql/postgres clients, we only evaluate the query after seeing `;`

**Comment by dantleech** [comment]
Makes sense.

**Comment by dantleech** [comment]
Created a pull request for this, although I don't think this is dangerous, as changes would only affect hte session.

**Comment by dbu** [comment]
ok, not that dangerous - if you notice what you did. you might still save after a weird situation if you don't really know what you are doing.
