### ISSUE TITLE
fix travis setup problem

### ISSUE THREAD

**Issue by dbu** [phpcr/phpcr-shell#170]
travis fails with "no output in the last 10 minutes". in the past, the problem was that there are too many versions of symfony that composer considers and it gets slow. as the tests already lock to symfony 2.6 i don't know if its the same issue. maybe we simple need to increase that timeout.

**Comment by dantleech** [comment]
This seems to be a general problem: https://github.com/composer/composer/issues/4121
/cc @lsmith77

**Comment by lsmith77** [comment]
add ``sudo: false`` to your .travis.yml file

**Comment by dantleech** [comment]
Seems no longer to be an issue, closing.
