### ISSUE TITLE
Latest version doesn't work

### ISSUE THREAD

**Issue by stopsopa** [phpcr/phpcr-shell#185]
I used phpcrsh.phar 1.0.0
and i've ended with this: http://i.imgur.com/ksiSk5y.png
after that i downloades older version 1.0.0-beta4 and it's work fine.

**Comment by dantleech** [comment]
Yes indeed. I upgraded the Symfony version, looks like there is a missing regression test, I will try and fix this soon.

In the meantime you can ommit the `-p` option and it should work.

**Comment by dantleech** [comment]
Fixed and released 1.0.1
