### ISSUE TITLE
Aliases not working 

### ISSUE THREAD

**Issue by alexander-schranz** [phpcr/phpcr-shell#187]
Not sure why but I get the following errors when using aliases in the phpcrshell

ls:

```bash
[2016-11-17 15:11:38] doctrine.DEBUG:                SELECT * FROM phpcr_nodes               WHERE
path = :path                 AND workspace_name = :workspace              
ORDER BY depth, sort_order ASC {":path":"/{arg1}",":pathd":"/{arg1}/%",":workspace":"default"
[PHPCR\PathNotFoundException] Item /{arg1} not found in workspace default
```

cd:
```bash
[Symfony\Component\Console\Exception\RuntimeException] Too many arguments, expected arguments "command" "path".
```

![bildschirmfoto 2016-11-17 um 15 07 24](https://cloud.githubusercontent.com/assets/1698337/20392550/98351c26-acd8-11e6-8202-80a1319e8d3c.png)

On older projects which use phpcr-shell before 1.0 it works correctly, but could also be the difference that old projects are on jackrabbit and doctrine.

**Comment by dantleech** [comment]
Did you customize the aliases?

Basically arguments are now passed verbatim to the aliased command as of [this pr](https://github.com/phpcr/phpcr-shell/pull/181/files).

This means that the old `{argX}` placeholders no longer server any purpose.

**Comment by dantleech** [comment]
You can just do `mv ~/.phpcrsh/aliases.yml ~/.phpcrsh/aliases.yml.back`, guess that might fix the issue.

**Comment by alexander-schranz** [comment]
@dantleech thank you! The file is only alias.yml but it did work: `mv ~/.phpcrsh/alias.yml ~/.phpcrsh/alias.yml.back`
