### ISSUE TITLE
Versionable check is too strict

### ISSUE THREAD

**Issue by middlebrain** [phpcr/phpcr-shell#190]
The check if a node is versionable is too strict (function `assertNodeIsVersionable` in file `/src/PHPCR/Shell/Console/Helper/NodeHelper.php`).

A node type without `mix:versionable` can be derived from a node type with 'mix:versionable'. E.g.  
```
[foo:bar] > nt:base, mix:versionable
[foo:baz] > foo:bar
```
The current versionable check throws an exception (`Node "%s" is not versionable`) for nodes of type `foo:baz`.

**Comment by dbu** [comment]
indeed. https://github.com/phpcr/phpcr-shell/blob/master/src/PHPCR/Shell/Console/Helper/NodeHelper.php#L35 should instead say `if ($mixinType->isNodeType($mixinTypeName)) {` to have phpcr handle the type inheritance checking. do you want to send a pull request for this?

**Comment by dbu** [comment]
fixed in #191
